### ISSUE TITLE
Implement the map phase that takes a set of patterns and creates different hashes

### ISSUE THREAD

**Issue by torito1984** [eirasf/KNiNe#4]
This map phase takes an RDD of patterns and a hasher element and flatMaps all the hash codes created. The hash codes have an associated "identifier". This identifier in the case of LSH is the identifier of the table that corresponds to that hash function

**Comment by eirasf** [comment]
This map is currently working but hasn't been tested and no layers of abstraction are implemented yet.

**Comment by eirasf** [comment]
Done. Added as an operation common to all LSHGraphBuilders.
